### ISSUE TITLE
[BUG] `python` apt package fails to install on Ubuntu 22

### ISSUE THREAD

**Issue by TechDufus** [TechDufus/FluxNodeInstall#62]
### Environment

Self-Hosted

### System

Ubuntu 22.04 LTS

### Version

latest main

### Describe the problem

When running against an Ubuntu 22 system, `sudo apt install python` gives the following error:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  2to3 python2-minimal python2 dh-python python-is-python3

E: Package 'python' has no installation candidate
```

### Additional info

And this is the verbose `-vvv` output of `ansible-playbook flux.yml` for the python install against an Ubuntu 22 system:
```error
The full traceback is:
  File "/tmp/ansible_ansible.builtin.apt_payload_sxorqpav/ansible_ansible.builtin.apt_payload.zip/ansible/modules/apt.py", line 526, in package_status
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 287, in __getitem__
    raise KeyError('The cache has no package named %r' % key)
failed: [puma-nimbus2] (item=python) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_change_held_packages": false,
            "allow_downgrade": false,
            "allow_unauthenticated": false,
            "autoclean": false,
            "autoremove": false,
            "cache_valid_time": 0,
            "clean": false,
            "deb": null,
            "default_release": null,
            "dpkg_options": "force-confdef,force-confold",
            "fail_on_autoremove": false,
            "force": false,
            "force_apt_get": false,
            "install_recommends": null,
            "lock_timeout": 60,
            "name": "python",
            "only_upgrade": false,
            "package": [
                "python"
            ],
            "policy_rc_d": null,
            "purge": false,
            "state": "present",
            "update_cache": null,
            "update_cache_retries": 5,
            "update_cache_retry_max_delay": 12,
            "upgrade": null
        }
    },
    "item": "python",
    "msg": "No package matching 'python' is available"
}
```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using the latest version of FluxNodeInstall
- [X] You've checked that this [issue hasn't already been raised](https://github.com/techdufus/FluxNodeInstall/issues?q=is%3Aissue)
- [X] You agree to the [code of conduct](https://github.com/techdufus/FluxNodeInstall/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by TechDufus** [comment]
Even when installing `python-is-python3` on the system, this issue persists.

**Comment by JKTUNING** [comment]
Python3 is installed by default on Ubuntu 22.04 - so it just needs python-is-python3 in the apt list when using 22.04.

**Comment by TechDufus** [comment]
FWIW this is an ubuntu 22 box that was upgraded from 20 LTS.... so if that's going to cause issues maybe it should be documented?

Seems really annoying though that VMs couldn't be upgraded..

**Comment by JKTUNING** [comment]
Just add python and python-is-python3 to the yolo packages.

https://github.com/TechDufus/FluxNodeInstall/blob/1a31b19dfb07bd3e74bb33cd1d8cf52b3e7df62c/vars.yml#L105

**Comment by TechDufus** [comment]
> Just add python and python-is-python3 to the yolo packages.
> 
> https://github.com/TechDufus/FluxNodeInstall/blob/1a31b19dfb07bd3e74bb33cd1d8cf52b3e7df62c/vars.yml#L105

what happens when python 2.7 is installed on ubuntu 20 and we install `python-is-python3`... will have to test if that breaks anything.

**Comment by TechDufus** [comment]
I feel like only installing `python-is-python3` should only be run IF the `python` package install fails... it fails on ubuntu 20 where python 2.* is installed.

Just tested yolo-installing `python-is-python3` WILL upgrade to `python 3.8.10` which we only want to do if python fails...

I'll add this to the `common-installPackages` but hard-code this python task(s) and remove it from the `apt.packages` list, not a good fit for yolo.
